main: 1043335

1043335:
	gcc 1043335_02.c -lpthread -o 1043335_02 

run :
	./1043335_02 number.txt 3

clean:
	rm 1043335_02 advmerge.txt advquick.txt bubbleSort.txt mergeSort.txt quickSort.txt

all: clean main run

start: main run


