main: 1043335

1043335:
	gcc -o 1043335_01 1043335_01.c -lrt    

run :
	./1043335_01 number.txt

clean:
	rm 1043335_01 advmerge.txt advquick.txt bubbleSort.txt mergeSort.txt quickSort.txt

all: clean main run

start: main run


